<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Helper\**" />
    <EmbeddedResource Remove="Helper\**" />
    <None Remove="Helper\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.JSInterop" Version="9.0.6" />
    <PackageReference Include="Microsoft.TeamFoundationServer.Client" Version="19.225.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataContext\DataContext.csproj" />
    <ProjectReference Include="..\DataModel\DataModel.csproj" />
  </ItemGroup>

</Project>
